#ifndef __SSSV_PATCH_SYMBOLS_H__
#define __SSSV_PATCH_SYMBOLS_H__

#include "sssv_patch_types.h"

extern DisplayList* gDisplayListContext;
extern FrameContextMinimal* gFrameContext;
extern u16 gDepthImage[];
extern VIDataMinimal gVIData;
extern u16 gIntroPerspNorm[2];
extern u16 gWorldPerspNorm;
extern s16 gSineTable256[256];
extern LevelConfigMinimal gLevelConfig;
extern FogMinimal gFogState;
extern u16 gCameraVisibilityMask[8];
extern u8 gLodDetailState;
extern s16 gScreenWidth;
extern s16 gScreenHeight;
extern s8 gAttractModeState;
extern VpRaw gMainViewport;
extern Gfx* gMainDL;
extern Gfx* gOpaqueDL;
extern Gfx* gXluDL;
extern Gfx* gLayer0DL;
extern Gfx* gLayer1DL;
extern Gfx* gAuxDL;
extern u8 gCurrentOverlay;
extern s16 gOverlayState;
extern Overlay2MenuState gOverlayMenuState;
extern s32 gIntroTransitionPending;
extern f32 recomp_get_target_aspect_ratio(f32 original_aspect);
extern s16 gHudTimerSeconds;
extern s16* gHudCenterText;
extern s16 gHudBarBaseY;
extern LevelProgressMinimal gLevelProgress;
extern u8 gHudTimerAscii[];
extern u8 gCameraUiState;
extern u8 D_803F2AA3;
extern u8 D_803F2C6C;
extern s8 D_803F2C6D;
extern UiFlowStateMinimal D_803F2D10;
extern s16* gTerminalStatText[20];
extern s16 gTerminalStatTextX[20];
extern char* gCreditsLines[];
extern s16 gCreditsEntryOffset;
extern s16 gCreditsVerticalPosition;
extern ScreenTransitionMinimal gScreenTransition;
extern TrigLutMinimal gTrigLut;
extern void* gMenuSegmentBase;
extern void* gFontSegmentBase;
extern void* gSegment1Base;
extern void* gSegment5Base;
extern ViewportStateMinimal gOverlayViewport;
extern OverlayLookAtMinimal gPauseMenuLookAt;
extern OverlayUiStateMinimal gOverlayUiState;
extern Gfx gOverlay3DRenderSetupDl[];
extern Gfx gWorldChunkLodSetupDl[];
extern Gfx gTerminalDnaOpaqueRenderSetupDl[];
extern Gfx gTerminalDnaInterlaceRenderSetupDl[];
extern Gfx gPrimitiveFillRenderSetupDl[];
extern Gfx gOpaqueLit3DRenderSetupDl[];
extern Gfx gSprite2DRenderSetupDl[];
extern Gfx gIntroLogoTextureSetupDl[];
extern Gfx gIntroLogoModelDl[];
extern Gfx gIntroRevealQuadDl[];
extern Lights1 gIntroLogoLight;
extern AnimalStateMinimal gAnimalState;
extern s16 gCurrentAnimalIndex;
extern char gDebugTextBuffer[];
extern s16 gFrameStepDivisor;
extern s16 gCheatInputCursor;
extern s16 gCheatInputNeutralLatch;
extern s16 gCheatInputDebounceTimer;
extern u8 gCheatLastButtonCode;
extern CheatsMinimal gCheats;

extern f32 gIntroCamEyeX;
extern f32 gIntroCamEyeY;
extern f32 gIntroCamEyeZ;
extern f32 gIntroScaleX;
extern f32 gIntroScaleY;
extern f32 gIntroScaleZ;
extern f32 gIntroCamUpX;
extern f32 gIntroCamUpY;
extern f32 gIntroCamUpZ;
extern u8 gspF3DEX_fifoTextStart[];
extern u8 gspF3DEX_fifoDataStart[];
extern u8 gspSprite2D_fifoTextStart[];
extern u8 gspSprite2D_fifoDataStart[];
extern f32 gIntroLogoPosX;
extern f32 gIntroLogoPosY;
extern f32 gIntroLogoPosZ;
extern f32 gIntroLogoRotX;
extern f32 gIntroLogoRotY;
extern f32 gIntroLogoRotZ;
extern f32 gCameraEyeWorldX;
extern f32 gCameraEyeWorldZ;
extern f32 gCameraEyeWorldY;
extern Gfx gFovMaskRenderSetupDl[];
extern Gfx gRestoreRgba16TextureLutDl[];
extern u8 img_fov_masks_ci4__png[];
extern ControllerMinimal D_80291090;
extern OSContPad* gControllerInput;
extern s16 gControllerDebounce;
extern u16 gTerminalFrameCounter;
extern s16 gTerminalFadeStep;
extern u8 gTerminalPhase;
extern u8 gTerminalTransitionCounter;
extern f32 D_803A6CC4_7B8374;
extern f32 D_803A6CC8_7B8378;
extern u8 D_803F6460;
extern s16 D_803F6468;
extern f32 D_803F646C;
extern s16 D_803F6470;
extern u8 D_803F6472;
extern TerminalTextScrollStateMinimal gTerminalTextScrollState;
extern s16* gTerminalStatLabels[18];
extern s32 sample_ground_height_at_xz(s16 x, s16 z);

extern s16 is_world_cell_loaded_6AB9E4(s32 arg0, s32 arg1, s32 arg2);
extern s16 classify_visibility_and_draw_fov_mask(s32 arg0, s32 arg1, s32 arg2, s32 arg3, u8 fovImageIdx, s16 red, s16 green, s16 blue, s8 arg8, u8 arg9);
extern s16 classify_visibility_simple(s32 arg0, s32 arg1, s32 arg2, s32 arg3, s8 arg4);
extern void update_world_camera_transform(void);
extern void switch_to_current_segment(Gfx** dl, DisplayList* ctx);
extern void init_f3dex_render(Gfx** dl, DisplayList* ctx);
extern void begin_f3dex_render(Gfx** dl, DisplayList* ctx);
extern void begin_f3dex_render_sync(Gfx** dl, DisplayList* ctx);
extern void setup_frame_render_state(DisplayList* ctx, Gfx** dl);
extern void load_segments(Gfx** arg0, DisplayList* arg1);
extern void clear_depth_buffer(Gfx** arg0);
extern void draw_sprite_with_prim_depth(Gfx** dl, uSprite* sprite, u16 width, u16 height, u16 scale_x, u16 scale_y, u8 flip_x, u8 flip_y, u16 p_screen_x, u16 p_screen_y, u16 prim_depth);
extern void build_rotate_scale_translate_matrix(Mtx* arg0, s32 arg1, s32 arg2, s32 arg3, s16 arg4, s16 arg5, s16 arg6, s32 arg7, s32 arg8, s32 arg9);
extern void draw_rectangle(Gfx** dl, s16 x0, s16 y0, s16 x1, s16 y1, u8 r, u8 g, u8 b, u8 alpha);
extern void render_title_screen_frame(FrameContextMinimal* arg0);
extern void recomp_patch_debug_u32(u32 tag, u32 a, u32 b, u32 c);
extern void display_score(Gfx** dl, u8* score, u16 x_offset, u16 y_offset);
extern void prepare_text(u8* src, s16* dst);
extern void load_default_display_list(Gfx** dl);
extern void set_menu_text_color(u8 r, u8 g, u8 b, u8 a);
extern void select_font(u8 arg0, u8 fontType, u8 shadow, u8 arg3);
extern void display_text_centered(Gfx** dl, s16* text, u16 x, u16 y, f32 width, f32 height);
extern void display_text_word_wrapped(Gfx** dl, s16* text, u16 xStart, u16 yStart, f32 arg4, f32 arg5, u8 lineHeight);
extern void display_text(Gfx** dl, s16* text, u16 x, u16 y, f32 width, f32 height);
extern void func_8012D374(Gfx** dl, s16* text, u16 x, u16 y, f32 width, f32 height, s16 maxChars);
extern s32 check_cheat_code(const u8* buttonPresses, const char* cheatCode);
extern void play_sound_effect(s16 id, s16 arg1, s16 volume, f32 pitch, u8 pan);
extern void cheat_activate_scale_pulse_effect(void);
extern void cheat_activate_energy_camera_effect(void);
extern void cheat_activate_big_head_effect(void);
extern void cheat_toggle_mystery_bear(void);
extern void cheat_clear_camera_effects(void);
extern s16 get_message_width(s16* text);
extern s16 get_raw_message_length(s16* text);
extern s32 sprintf(char* dst, const char* fmt, ...);
extern s16 gControllerConnected;
extern s16 gNoControllerMessageText[];
extern void set_tv_mode_normal(void);
extern void render_screen_transition_tv_702A68(void);
extern void spin_dna_helixes(u16 arg0);
extern u16 advance_random_seed(void);
extern void start_sequence_volume_fade(s16 arg0, f32 arg1, f32 arg2, f32 arg3);
extern void start_sfx_volume_fade(f32 arg0, f32 arg1, f32 arg2);
extern void func_80137168(void);
extern void func_8013724C(s16 arg0);
extern void func_802F2EEC_70459C(s16 arg0, s16 arg1, s16 arg2, s16 arg3, s16 arg4, s16 arg5, s16 arg6);
extern void func_8032C2D0_73D980(s16 id, s16 volume, f32 pitch);
extern void func_8032CD20_73E3D0(s16 arg0, s16 arg1, f32 arg2, s16 arg3, f32 arg4);
extern void func_8038CF90_79E640(void);
extern void render_terminal_background_glyphs(Gfx** dl, u16 arg1);
extern void update_terminal_scene_lighting(u8 arg0);
extern void render_terminal_stat_text(s32 arg0, s32 arg1);

#endif
